apiVersion: apps/v1
kind: Deployment
metadata: { name: mysql }
spec:
  selector:
    matchLabels: { app: mysql }
  template:
    spec:
      containers:
      - name: mysql
        image: mysql:9
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: { secretKeyRef: { name: app-secret, key: MYSQL_PASSWORD } }
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
kind: Service
metadata: { name: mysql }
spec:
  ports: [ { port: 3306 } ]
  selector: { app: mysql }
