name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login -u sagar592 -p dckr_pat_b8mQisAbkaZc5rgwSd-7KgoqLZI

      - name: Build and push Docker image
        run: |
          docker build -t sagar592/my-php-app .
          docker push sagar592/my-php-app
